
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers/providers";
import {Toaster} from "sonner";
import {auth} from "@/auth";
import {SessionProvider} from "next-auth/react";
import {Modal} from "@/components/modal";
import {SubscriptionAlert} from "@/features/subscriptions/components/subscription-alert";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


      const session = await auth();
      return (
          <SessionProvider session={session}>
                <html lang="en">
                  <body className={inter.className}>
                      <Providers>
                          <Modal />
                          <Toaster />
                          <SubscriptionAlert />
                          { children }
                      </Providers>
                  </body>
                </html>
          </SessionProvider>
  );
}
