import { AIModel } from './types';

export const CHAT_MODELS: AIModel[] = [
  {
    id: 'anthropic/claude-3.7-sonnet',
    name: 'Claude 3.7 Sonnet',
    provider: 'anthropic',
    providerLabel: 'Anthropic',
    category: 'text',
    description: 'Modèle hybride raisonnement & design de référence.',
    badge: 'Recommandé',
    isPopular: true,
    contextWindow: '200k',
  },
  {
    id: 'anthropic/claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'anthropic',
    providerLabel: 'Anthropic',
    category: 'text',
    description: 'Expertise graphique et composition créative prouvée.',
    isPopular: true,
    contextWindow: '200k',
  },
  {
    id: 'openai/gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    providerLabel: 'OpenAI',
    category: 'text',
    description: 'Ultra rapide, multimodal et polyvalent.',
    isPopular: true,
    contextWindow: '128k',
  },
  {
    id: 'openai/gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    providerLabel: 'OpenAI',
    category: 'text',
    description: 'Réponse instantanée et ultra économique.',
    badge: 'Rapide',
    contextWindow: '128k',
  },
  {
    id: 'google/gemini-2.0-flash-001',
    name: 'Gemini 2.0 Flash',
    provider: 'google',
    providerLabel: 'Google',
    category: 'text',
    description: 'Vitesse de génération fulgurante et haute précision.',
    badge: 'Éclair',
    isPopular: true,
    contextWindow: '1M',
  },
  {
    id: 'deepseek/deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'deepseek',
    providerLabel: 'DeepSeek',
    category: 'text',
    description: 'Raisonnement profond et logique de composition avancée.',
    badge: 'Raisonnement',
    isPopular: true,
    contextWindow: '64k',
  },
  {
    id: 'mistralai/mistral-large-2411',
    name: 'Mistral Large 2',
    provider: 'mistral',
    providerLabel: 'Mistral AI',
    category: 'text',
    description: "Modèle phare européen d'excellence en langue française.",
    contextWindow: '128k',
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B',
    provider: 'meta',
    providerLabel: 'Meta',
    category: 'text',
    description: 'La référence Open-Source la plus performante.',
    contextWindow: '128k',
  },
];

export const IMAGE_MODELS: AIModel[] = [
  {
    id: 'black-forest-labs/flux-1-schnell',
    name: 'FLUX.1 Schnell',
    provider: 'black-forest-labs',
    providerLabel: 'Black Forest Labs',
    category: 'image',
    description: 'Génération ultra-rapide en 4 étapes, netteté photoréaliste.',
    badge: 'Préféré',
    isPopular: true,
  },
  {
    id: 'black-forest-labs/flux-1-dev',
    name: 'FLUX.1 Dev',
    provider: 'black-forest-labs',
    providerLabel: 'Black Forest Labs',
    category: 'image',
    description: 'Qualité studio haute définition et rendu typographique propre.',
  },
  {
    id: 'stability-ai/stable-diffusion-3.5-large',
    name: 'Stable Diffusion 3.5 Large',
    provider: 'stability',
    providerLabel: 'Stability AI',
    category: 'image',
    description: 'Créativité artistique et composition stylisée.',
  },
];

export const DEFAULT_CHAT_MODEL = 'anthropic/claude-3.7-sonnet';
export const DEFAULT_IMAGE_MODEL = 'black-forest-labs/flux-1-schnell';
